import type { Metadata } from "next";
import localFont from "next/font/local";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import TestIcon from '../Logo.png';
import './index.css';
import RespProvider from './_components/RespProvider';

const testSoehne = localFont({
  src: [
    {
      path: "../Fonts/Test web fonts (WOFF2)/test-soehne-buch.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../Fonts/Test web fonts (WOFF2)/test-soehne-buch-kursiv.woff2",
      weight: "400",
      style: "italic",
    },
  ],
  variable: "--font-soehne",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${testSoehne.variable} ${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <RespProvider>
          <section className="header-comp">
            <Image className="testIcon" src={TestIcon} alt="test-icon" />
            <div className="title-cont">
              <h1>alkye</h1>
              <span>The easiest test you will ever do</span>
            </div>
          </section>
          {children}
        </RespProvider>
      </body>
    </html>
  );
}
